// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnehtpztldzemoyobzcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuZWh0cHp0bGR6ZW1veW9iemNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTUzMzEsImV4cCI6MjA3MzA5MTMzMX0.K-DIvL5IjAoQXiG61Bvuz_uYP13hsAsnk5W_I4mOX4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});